[package]
name = "flappy_dragon"
version = "0.1.0"
edition = "2021"
authors = ["Art Rosnovsky <artem@rosnovsky.us>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.1"
